
service: nwVerapi

# you can overwrite defaults here
stage: ${self:provider.stage}
region: ${self:provider.region}

provider:
  name: aws
  runtime: python2.7

plugins:
  - serverless-crypt

custom:
  cryptKeyId: ${env:AWS_KMS_KEYID}

# Function Lambda for veracode
functions:
  nwVerapiPost:
    handler: handler.lambda_function_postfiles
    name: nwVerapi-postFiles
    description: Veracode API For upload and scan
    runtime: python2.7
    memorySize: 512
    timeout: 30
    environment:
      USERNAME: ${file(properties.yml):username}
      PASSWORD: ${file(properties.yml):password}
    region: ${file(properties.yml):aws-region}
    vpc:
      securityGroupIds:
        - ${file(properties.yml):aws-lambda-sg}
      subnetIds:
        - ${file(properties.yml):aws-lambda-subnet1}
        - ${file(properties.yml):aws-lambda-subnet2}

    events:
      - http:
          path: api/nwVerapi/sendFiles
          method: post
          integration: lambda
#          authorizer:
#            type: aws_iam

  nwVerapiGet:
    handler: handler.lambda_function_getresults
    name: nwVerapi-getResults
    description: Veracode API Get results
    runtime: python2.7
    memorySize: 512
    timeout: 30
    environment:
      USERNAME: ${file(properties.yml):username}
      PASSWORD: ${file(properties.yml):password}
    region: ${file(properties.yml):aws-region}
    vpc:
      securityGroupIds:
        - ${file(properties.yml):aws-lambda-sg}
      subnetIds:
        - ${file(properties.yml):aws-lambda-subnet1}
        - ${file(properties.yml):aws-lambda-subnet2}
    events:
      - http:
          path: api/nwVerapi/getResults/{appid}
          method: get
          integration: lambda
#          authorizer:
#            type: aws_iam
