
service: nwVerapi # NOTE: update this with your service name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

# you can overwrite defaults here
stage: ${self:provider.stage}
region: ${self:provider.region}

provider:
  name: aws
  runtime: python2.7

plugins:
  - serverless-crypt

custom:
  cryptKeyId: ${env:AWS_KMS_KEYID}

functions:
  nwLambdaVerapi:
    handler: handler.lambda_function
    name: nwVerapi
    description: Veracode API For upload and scan
    runtime: python2.7
    memorySize: 512
    timeout: 30

    environment:
      username: ${self:custom.cryptKeyId.username}
      password: ${self:custom.cryptKeyId.password}
    events:
      - http:
          path: api/nwVerapi
          method: post
          integration: lambda

    resources:
      Resources:
        ApiGatewayMethodnwVerapiPost:
           Properties:
             AuthorizationType: AWS_IAM



