---
swagger: "2.0"
info:
  version: "2017-07-24T16:04:16Z"
  title: "test-nwVerapi"
host: "z90rihs6ie.execute-api.us-east-2.amazonaws.com"
basePath: "/uat"
schemes:
- "https"
paths:
  /api/nwverapi:
    post:
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
      security:
      - sigv4: []
securityDefinitions:
  sigv4:
    type: "apiKey"
    name: "Authorization"
    in: "header"
    x-amazon-apigateway-authtype: "awsSigv4"
definitions:
  Empty:
    type: "object"
    title: "Empty Schema"
